// examples/tanstack-start/src/routes/dark.tsx
import {
  Link,
  createFileRoute,
} from '@tanstack/react-router';

export const Route = createFileRoute('/dark')({
  staticData: {theme: 'dark'},
  component: DarkPage,
});

function DarkPage() {
  return (
    <div className="flex min-h-screen w-full items-center justify-center px-6">
      <Link
        className="text-lg underline underline-offset-4"
        to="/"
      >
        Go back
      </Link>
    </div>
  );
}

// examples/svelte/src/routes/dark/+page.svelte
<div
  class="flex min-h-screen w-full items-center justify-center px-6"
>
  <div class="space-y-6 text-center">
    <p
      class="text-sm uppercase tracking-[0.3em] text-black/50 dark:text-white/50"
    >
      Forced theme route
    </p>
    <h1 class="text-4xl font-semibold">Always dark</h1>
    <p
      class="max-w-md text-sm leading-relaxed text-black/60 dark:text-white/60"
    >
      The theme is pinned to dark here, but cookie
      updates still sync in the background.
    </p>

    <a
      class="inline-block underline underline-offset-4"
      href="/"
    >
      Go back home
    </a>
  </div>
</div>
