// examples/nuxt/app/components/theme-switcher.vue
<script setup lang="ts">
import {computed} from 'vue';
import type {
  LightOrDark,
  WithSystem,
} from 'ssr-themes';
import {useTheme} from '../lib/theme';

type ThemeName = WithSystem<LightOrDark>;

const {forced, setSelected, selected, system} =
  useTheme();
const codeClassName =
  'rounded bg-black/5 px-1 py-0.5 dark:bg-white/10';

const selectedTheme = computed(
  () => selected.value ?? 'system',
);
const deviceTheme = computed(
  () => system.value ?? 'dark',
);
const suggestedTheme = computed(() =>
  deviceTheme.value === 'dark' ? 'light' : 'dark',
);

const handleChange = (event: Event) => {
  const select =
    event.currentTarget as HTMLSelectElement;
  setSelected(select.value as ThemeName);
};
</script>

<template>
  <select
    id="theme-selector"
    class="rounded border border-current bg-transparent px-3 py-2 text-xl"
    :disabled="Boolean(forced)"
    aria-label="Theme"
    data-test-id="theme-selector"
    @change="handleChange"
  >
    <option
      value="system"
      :selected="selectedTheme === 'system'"
    >
      System
    </option>
    <option
      value="dark"
      :selected="selectedTheme === 'dark'"
    >
      Dark
    </option>
    <option
      value="light"
      :selected="selectedTheme === 'light'"
    >
      Light
    </option>
  </select>

  <p
    class="mx-auto max-w-lg text-sm leading-relaxed text-black/60 dark:text-white/60"
  >
    Try
    <code :class="codeClassName">{{
      suggestedTheme
    }}</code
    >, refresh the page, and check that the select
    never briefly shows
    <code :class="codeClassName">{{
      deviceTheme
    }}</code>
    first.
  </p>
</template>

// examples/next/app/theme-switcher.tsx
'use client';

import {bindTheme} from 'ssr-themes/react';

import {theme} from './theme';

const {useTheme} = bindTheme(theme);

const codeClassName =
  'rounded bg-black/5 px-1 py-0.5 dark:bg-white/10';

export default function ThemeSwitcher() {
  const {selected, setSelected, forced, system} =
    useTheme();

  const disabled = Boolean(forced);
  const value = selected ?? 'system';
  const deviceTheme = system ?? 'dark';
  const suggestedTheme =
    deviceTheme === 'dark' ? 'light' : 'dark';

  return (
    <>
      <select
        id="theme-selector"
        className="rounded border border-current bg-transparent px-3 py-2 text-2xl"
        value={value}
        onChange={event =>
          setSelected(
            event.target.value as NonNullable<
              typeof selected
            >,
          )
        }
        disabled={disabled}
        aria-label="Theme"
        data-test-id="theme-selector"
      >
        <option value="system">System</option>
        <option value="dark">Dark</option>
        <option value="light">Light</option>
      </select>

      <p className="mx-auto max-w-lg text-sm leading-relaxed text-black/60 dark:text-white/60">
        Try{' '}
        <code className={codeClassName}>
          {suggestedTheme}
        </code>
        , refresh the page, and check that the select
        never briefly shows{' '}
        <code className={codeClassName}>
          {deviceTheme}
        </code>{' '}
        first.
      </p>
    </>
  );
}
